# ===== CAMERA =====
FRAME_WIDTH = 320
FRAME_HEIGHT = 240
FPS_TARGET = 12

# ===== DETECTION =====
MODEL_PATH = "models/yolov8n.onnx"
DETECTION_INTERVAL = 5
CONF_THRESHOLD = 0.4
NMS_THRESHOLD = 0.45

# ===== TRACKING =====
USE_CSRT_FALLBACK = True

# ===== CONTROL =====
CP = 0.6
MAX_STEP = 2.0  # degrees per frame
DEAD_ZONE = 0.05  # 5%

SMOOTHING_ALPHA = 0.85

SERVO_MIN = 0
SERVO_MAX = 180
SERVO_CENTER = 90

# ===== BEHAVIOR =====
TARGET_LOCK_TIME = 5.0
HOLD_TIME = 0.5
LOST_TIMEOUT = 2.0

# ===== IDLE SCAN =====
SCAN_SPEED = 0.5  # deg/frame
SCAN_MIN = 60
SCAN_MAX = 120

# ===== TARGET SELECTION =====
W_RECENCY = 2.0
W_SIZE = 1.0
W_CENTER = 0.5